# Generated by Django 3.2.9 on 2021-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depId', models.IntegerField()),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('CNIC', models.CharField(max_length=20)),
                ('contact_No', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
