# Generated by Django 3.2.9 on 2021-11-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='FatherName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='Name',
        ),
        migrations.AlterModelTable(
            name='department',
            table='sbk_department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='sbk_employee',
        ),
    ]
