# Generated by Django 3.2.9 on 2021-11-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbkApp', '0002_auto_20211104_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depId',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Information Technology'), (3, 'English')]),
        ),
    ]
